OSGeo/shapelib

- dbfopen.c
- shapefil.h
- shpopen.c
Guard DBFFlushRecord and SHPWriteObject FSeek calls with an FTell check for whether we are already at the correct position (a common case). Avoids defeating write buffering on network filesystems; example observed speedups of 2x on NFS and 45x on GlusterFS.
> Prevent no-op FSeeks writing dbf & shp records for network filesystem performance

- dbfdump.c
Users likely won't care if things aren't cleaned up correctly before returning from main, as the process ending will release all resources.  However, leak checkers flag it.
I hit this when trying to use a stripped down version of dbfdump for fuzzing
Mostly, this or is me trying out GitHub's web editing capabilities from a phone.
> dbfdump.c: Close the dbf handle if there are no fields

- .github/workflows/main.yml
- CMakeLists.txt
Reenable CMake testing by forcing old behavior
This is a temporary solution to get CMake testing working again. With
https://github.com/OSGeo/shapelib/commit/20ce54023f1ed9b320fe5bc06fd746d72de06892 set:
there were several variations of this error:
```
CMake Error at CMakeLists.txt:220 (get_target_property):
The LOCATION property may not be read from target "shpcreate".  Use the
target name directly with add_custom_command, or use the generator
expression $<TARGET_FILE>, as appropriate.
```
See https://github.com/mapserver/mapserver/issues/5646
Skipped getting Windows testing working:
```
test 1
Test not available without configuration.  (Missing "-C <config>"?)
Start 1: test2
Test not available without configuration.  (Missing "-C <config>"?)
```
> Reenable CMake testing by forcing old behavior

- shputils.c
This switch from using `strncpy` to `memcpy`.
A similar switch has already been made [here](https://github.com/OSGeo/shapelib/blob/21ae8fc16afa15a1b723077b6cec3a9abc592f6a/dbfopen.c#L1310-L1311).
Without this fix (or one like it), `strncpy` yields warnings:
```
shputils.c:403:57: warning: 'strncpy' output may be truncated copying 39 bytes from a string of length 39 [-Wstringop-truncation]
shputils.c:404:57: warning: 'strncpy' output may be truncated copying 39 bytes from a string of length 39 [-Wstringop-truncation]
```
> Change strncpy to memcpy

- CMakeLists.txt
Use this as a cache variable to allow it to be overridden by users and other projects. There are better practices for enabling / disabling tests in CMake. It's normal to include a check for whether or not this project is top-level and disable building tests by default. It's also recommended to provide a project-specific variable for controlling building tests or not.
I've kept this change minimal for now, however.
This makes integration with the Conan package manager easier.
> Use the the standard BUILD_TESTING CMake variable

- CMakeLists.txt
The `FATAL_ERROR` keyword is no longer required in CMake 3.x.
> Move cmake_minimum_required before project command

- CMakeLists.txt
The GitHub hosted runners for MSVC have Bash and apparently sed, too. This causes tests to be built when using MSVC on Windows incorrectly.
This PR moves the check for MSVC which disables tests before the check for Bash and sed. This ensures that the CMake cache variable is set properly for MSVC.
> Disable running tests on MSVC even with Bash and sed

- dbfadd.c
- dbfcreate.c
- dbfdump.c
- dbfopen.c
- safileio.c
- sbnsearch.c
- shapefil.h
- shpadd.c
- shpcreate.c
- shpdump.c
- shpopen.c
- shptest.c
- shptree.c
- shptreedump.c
- shputils.c
This is causing problems with visual studio and clang.  I believe it is unused as the git doesn't support keyword substitution.
For example:
```
C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\Llvm\x64\bin\clang-cl.exe   -D_CRT_NONSTDC_NO_WARNINGS -D_CRT_SECURE_NO_WARNINGS -IC:\Users\user1\source\repos\whit2\out\build\x64-Clang-Debug -IC:\Users\user1\source\repos\whit2 -IC:\Users\user1\source\repos\whit2\shape -m64 -fdiagnostics-absolute-paths  /DWIN32 /D_WINDOWS /W3 /MDd /Zi /Ob0 /Od /RTC1 /std:c17 -Wno-unused-but-set-variable /showIncludes /FoCMakeFiles\shp.dir\shapelib\safileio.c.obj /FdCMakeFiles\shp.dir\shp.pdb -c -- C:\Users\user1\source\repos\whit2\shapelib\safileio.c
C:\Users\user1\source\repos\whit2\shapelib\safileio.c(77,1): warning : all paths through this function will call itself …
```
> remove SHP_CVSID.

- CMakeLists.txt
Adds -Wall -Wextra -pedantic compiler flags for non-MSVC builds.
With clang-13 and gcc-11 this does not reveal any new warnings in either cmake's Release or Debug mode.
pedantic yields:
```
/home/rick/projects/contributing/shapelib/safileio.c:46:18: warning: ISO C does not allow extra ‘;’ outside of a function [-Wpedantic]
46 | SHP_CVSID("$Id$");
```
> Add -Wall -Wextra -pedantic as compiler flags

- safileio.c
- shapefil.h
This is a quick fix to add support for 64-bit file I/O on Windows for MSVC. Let me know if I should do better.
> Add MSVC quick fix for LFS

- dbfopen.c
- sbnsearch.c
- shapefil.h
- shpopen.c
- shptree.c
Note, that this changes the API actually.
> Pass hooks as const pointer

- contrib/shpgeo.c
These fixes the warnings reported by Clang compiler.
> Fix bit-wise comparison, comment and NULL check

- cmake/contrib.cmake
- contrib/csv2shp.c
By removing the regex dependency csv2shp could easily be generalized to also build with MSVC.
> Enable csv2shp build with MSVC

- LICENSE-LGPL
- LICENSE-MIT
- Makefile.am
- contrib/ShapeFileII.pas
- contrib/Shape_PointInPoly.cpp
- dbfadd.c
- dbfcreate.c
- dbfdump.c
- dbfopen.c
- safileio.c
- sbnsearch.c
- shapefil.h
- shpadd.c
- shpcreate.c
- shpdump.c
- shpopen.c
- shprewind.c
- shptest.c
- shptree.c
- shptreedump.c
- shputils.c
- web/license.html
* Make dual-license more transparent (at first sight)
* LICENSE-LGPL was taken from https://www.gnu.org/licenses/old-licenses/lgpl-2.0.txt
* Replace "MIT style" by just "MIT"
* Prefer SPDX license identifier
> Improve license visibility

- dbfopen.c
- sbnsearch.c
- shapefil.h
- shpopen.c
- Polygon writing: avoid considering rings slightly overlapping as inner-outer
rings of others (refs OSGeo/gdal#5315)
https://github.com/OSGeo/gdal/commit/a41e0a2b163b8c4b33ecf0f93f7cc487b9902b61
- Polygon writing: consider rings at non-constant Z as outer rings
(fixes OSGeo/gdal#5315)
As noted in code comments, this is an approximation of more complicated
tests we'd likely have to do, that would take into account real
co-planar testing, to allow detecting inner rings of outer rings in an
oblique plane.
https://github.com/OSGeo/gdal/commit/702b19f91ba8065df2fa5d74f31fcdf798e0a838
- shpopen.c: Communicate why the file size cannot be reached when appending
features (OSGeo/gdal#4140)
Clearly state why the file size cannot be reached. This is important in order
to correctly inform the user …
> Merge GDAL changes into upstream shapelib

- dbfopen.c
- safileio.c
- sbnsearch.c
- shapefil.h
- shpopen.c
- shptree.c
This PR adds an additional `void*` to the `SAHooks` struct and passes it along to the file open/close hooks. It is set to a `NULL` pointer by default, but enables opening/closing files with additional context, e.g. a filesystem abstraction or thread-local state.
> add userdata ptr to SAHooks, available during file open/removal

- CMakeLists.txt
If you don't want to build the executables, set BUILD_SHAPELIB_EXECUTABLES to OFF when configuring with CMake.
> Make building executables optional with CMake.

- safileio.c
This got "broken" by 01ee129f7d53b2619b2a1e8e5e5ea2553caaaf67.
You can see these warnings in https://github.com/OSGeo/shapelib/actions/runs/7152273225/job/19477427836. 
> D:/a/shapelib/shapelib/safileio.c(168,20): warning C4113: 'SAFile (__cdecl *)(const char *,const char *)' differs in parameter lists from 'SAFile (__cdecl *)(const char *,const char *,void *)' [D:\a\shapelib\shapelib\build\shp.vcxproj]
D:/a/shapelib/shapelib/safileio.c(169,21): warning C4113: 'int (__cdecl *)(const char *)' differs in parameter lists from 'int (__cdecl *)(const char *,void *)' [D:\a\shapelib\shapelib\build\shp.vcxproj]
> Fix UTF8 hook functions

- shpopen.c
CPL_UNUSED only was used in one place
> Ensure consistent definition and declaration of SHPRewindObject

- .github/workflows/main.yml
- CMakeLists.txt
- sbnsearch.c
See https://github.com/OSGeo/shapelib/pull/82#issuecomment-1903963244
> CI: treat all warnings as errors

- CMakeLists.txt
- shpopen.c
It's already correct in the other place:
https://github.com/OSGeo/shapelib/blob/8cf92b255f282eeeb3580e84c6fe56257c9068f3/shpopen.c#L842
I wonder why this is not reported by GCC with -Wall set.
> Fix format specifier

- CMakeLists.txt
- configure.ac
- sbnsearch.c
- shapefil.h
- shpopen.c
- shptree.c
This is a mix of both static (shapefil.h) and dynamic (CMake and autoconf) configuration to detect BIG endian architectures at compile time or configure time, respectively.
The static variable bBigEndian is removed,
Refactoring was not straight-forward since in some code locations Swap is called for big endian, in other locations for little endian. This looks kind of dangerous and error-prone to me. Edit: OK, it is mixed endianness by design.
Resolves #36
> Detect byte order at compile time

- dbfopen.c
- shapefil.h
- shapelib.def
No special handling is done - just the wrappers (for the underlying attribute storage) are added in a straight-forward implementation.
Resolves #16
> Add wrapper functions for read/write of date attributes

- CMakeLists.txt
- Makefile.am
- dbfopen.c
- sbnsearch.c
- shapefil_private.h
- shpopen.c
- shptree.c
Get rid of multiple definitions of SwapWord in favour of built-in swap functions.
> Prefer builtin swap functions

- dbfopen.c
- sbnsearch.c
- shapefil.h
- shpopen.c
- shptree.c
> Fix const-correctness

- dbfopen.c
Fix for #98. Date value should not be reformatted.
> Fix writing Date value to DBF

- dbfopen.c
In addition to #98: Call DBFReadAttribute directly instead of confusing DBFReadStringAttribute.
> Do not call DBFReadStringAttribute in DBFReadDateAttribute

- README.CMake
Would be preferable to have a proper Markdown file instead of the confusing CMake extension. Alternatively, this could go well to a proper README.md.
Resolves #100
> Fix README.CMake

- configure.ac
This fixes the warning
> configure.ac:62: warning: AC_C_BIGENDIAN should be used with AC_CONFIG_HEADERS
> Fix configure warning

- tests/dbf_test.cc
In addition to #98: Add the missing (and requested) unit tests.
> Add unit tests for DBFReadDateAttribute/DBFWriteDateAttribute

- dbfopen.c
- tests/dbf_test.cc
Do not ignore invalid logical character. Only 'F' and 'T' are supported.
> Return false when writing unsupported logical value

- contrib/dbfcat.c
Changes:
* Avoid uninitialized memory in message
* Fix date and logical fields
* Fix 160 character limit for passed file names
Breaking changes:
* Pass file names as is (i.e., no more magic with file extension)
* Ignore deleted records
* Print error messages to stderr
> Make dbfcat usable

- tests/CMakeLists.txt
Makes it easier to set/overwrite C++ standard on command line.
> Prefer target property to set C++ standard

- .github/workflows/main.yml
- tests/CMakeLists.txt
Neither necessary nor desired.
> Disable building GMock and installation of GTest

- dbfopen.c
Fixes https://github.com/OSGeo/gdal/issues/10405
> DBFIsValueNULL(): accept empty string as NULL Date

- dbfopen.c
- tests/dbf_test.cc
It is possible to write a NULL Date by `DBFWriteNULLAttribute` where a subsequent call to `DBFIsAttributeNULL` returns false due to handling only `"0"` and `"00000000"` as valid NULL Date strings. This is fixed by writing NULL Date independently of the field width.
Edit: There are other fixes possible, e.g. for width of 1 and 8 to be more backward-compatible w.r.t. binary content or by considering the field width when reading the Null string.
> Fix API inconsistency of NULL Date

- Makefile.am
- cmake/shapelib.gta.runsettings.in
- tests/CMakeLists.txt
This PR generates the Run Settings file for the GoogleTestAdapter (GTA) with the expected working directory to run the GoogleTest based unit tests from Test Explorer in Visual Studio.
Resolves #143
> CMake: Add GTA Run Settings

- .github/workflows/main.yml
- CMakeLists.txt
- tests/CMakeLists.txt
This PR fixes the DLL paths for the testsuite (both GoogleTest based unittests and script-based tests) when built with CMake shared libs for MSVC and CygWin.
I tried a lot actually. In the end the solution from https://stackoverflow.com/a/72341403/8520615 worked out.
Additionally
- the special cases and workarounds in the CMake CI builds are removed from the GitHub Actions.
- the ctest option [--no-tests](https://cmake.org/cmake/help/latest/manual/ctest.1.html#cmdoption-ctest-no-tests)=error was added to not silently accept CI builds with -DBUILD_TESTING=**OFF** (as I did by accident during refactoring).
Resolves #142
> CMake ≥ 3.21: Fix ctest paths for shared libs (MSVC and CygWin)

- .github/workflows/main.yml
- CMakeLists.txt
- tests/CMakeLists.txt
As proposed here: https://github.com/OSGeo/shapelib/pull/146#discussion_r1714312120
This fails as expected due to #142 (being addressed by #146).
> Enable build of both shared and static libs via GitHub Actions

- shpdump.c
- shptest.c
- shptreedump.c
In addition to 6a69e2794a99c70461327e4ceb4350dd2dbe57ef where USE_DBMALLOC was removed from shapefil.h
> Remove USE_DBMALLOC completely

- contrib/tests/shpproj.sh
As reported by https://github.com/OSGeo/shapelib/pull/111#issuecomment-2286097239.
> Fix diff command to only set --strip-trailing-cr if available

- web/dbf_api.html
- web/shp_api.html
I only touched the existing functions (to gain at least consistency) but won't add the missing API functions.
> API doc: Fix const-correctness

- Makefile.am
- tests/CMakeLists.txt
- tests/shp_bench.cc
This PR demonstrates the advantage of SHPSetFastModeReadObject (for serial iteration of shape objects) because I wanted to see some actual bench mark numbers.
It adds Google Benchmark as another test dependency. I needed very latest HEAD https://github.com/google/benchmark/commit/c19cfee61e136effb05a7fc8a037b0db3b13bd4c of today to work around a Win compiler warning (treated as error).
> Run benchmark on SHPSetFastModeReadObject

- tests/dbf_test.cc
This was unexpected, but good to have it confiirmed via unit test.
> Add test that field names do not have to be unique

- CMakeLists.txt
- tests/CMakeLists.txt
1. CTest dependency is not required and considered controversial because it introduces extra build targets
2. Google Benchmark can no longer be downloaded with shallow flag set
> Update CMake build dependencies: Remove include(CTest) (/w enable_testing() still set) and fix Google Benchmark 

- tests/CMakeLists.txt
With Google Benchmark [v1.9.1](https://github.com/google/benchmark/releases/tag/v1.9.1) available we can switch to a released version and shallow clone again.
> Prefer tagged version of Google Benchmark

- dbfadd.c
- dbfcreate.c
- tests/expect3.out
- tests/test3.sh
> dbfcreate: allow creation of Date and Logical fields #167

- CMakeLists.txt
Two minor cmake tweaks:
1. Add a guard against multiple inclusions which might happen when part of larger builds.
2. Make the BUILD_TESTING variable an option which can be set by user.
These changes should AFAICT be backwards compatible.
Exported from the opencpn project at github.com://opencpn/opencpn (Well, not really now, but soon).
> Build: cmake polish, notably BUILD_TESTING option
